[package]
name = "sxutil"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
protobuf-codegen = "3.2.0"
protoc-bin-vendored = "3.0.0"

[dependencies]
build-time = "0.1.3"
git-version = "0.3.5"
protobuf = "3.2.0"
rs-snowflake = "0.6.0"
synerex_api = { git = "https://github.com/exdata-inc/synerex_api/", branch = "feature/rust"}
synerex_nodeapi = { git = "https://github.com/exdata-inc/synerex_nodeapi/", branch = "feature/rust"}
tonic = "0.9.2"
